### ISSUE TITLE
Unable to add Juniper device

### ISSUE THREAD

**Issue by Jmahaja1** [cherifimehdi/Graphical_Check_Access#1]
Hello,

It's a great script but for some reason it won't let me add a Juniper device? Any clues? Does the ho
![image](https://user-images.githubusercontent.com/61688610/142887253-f3210d6f-4774-486e-b0ae-7570451a784a.png)
![image](https://user-images.githubusercontent.com/61688610/142887430-d1a27665-f04e-4e70-bee0-9a6f531181a7.png)
![image](https://user-images.githubusercontent.com/61688610/142887789-e17d79e3-7009-4ec6-8b26-ab79cbbbd658.png)

Also it is not showing the picture for switch. I have checked switch.jpg exists in static folder.

**Comment by cherifimehdi** [comment]
Hello, Thank you very much for the remark
For the Switch, because in static folder the Switch image is in "jpg" extention and in the script it is in "png" extention (When I tested it). Now I updated the extention in the script "graphical_check_access.py " in line 29
About juniper, personally I never tested it on juniper Switchs or Routers but I think it will work. I will check for this. 
Please let me know if there is another remark and if it works for the Switch
Thank you

**Comment by Jmahaja1** [comment]
Thank you for your prompt response. :)

Yes, I'm able to see the switch now after changing the format to jpg in the "graphical_check_access.py" script.
I can also see Juniper router learnt in the final topology along with the switch but only in the Topology_Result.png file under static folder and not on the web page despite refreshing it.


![image](https://user-images.githubusercontent.com/61688610/142926537-e928a8ef-2f39-4ff8-9664-42bb6fe2f81f.png)

![image](https://user-images.githubusercontent.com/61688610/142926945-62e61ad5-c232-46e3-a43e-d1ab33955e7e.png)

![image](https://user-images.githubusercontent.com/61688610/142926901-c2499c7b-4cd5-40fe-85c4-46d5410a87eb.png)

**Comment by Jmahaja1** [comment]
Hello, I figured out what's causing the issue. Although the network drawing is updated once it detects the changes, the web page is not updated automatically unless we delete the cookies and reload the page. I wonder if this step could be automated. Thanks again for your scripts. It's very useful.

**Comment by cherifimehdi** [comment]
Hello,
I am happy you found it useful and thank you for your remarks.
As I mentioned in Readme file in "Important remarks" section, there is a way to automate the web page refreshing which lead to trigger the check access to see periodically the state of the devices access. You can use some solutions such as: Tab Reloader,  pyautogui or selenium. 
The improvment of this project is still open.
Thank you again
